### ISSUE TITLE
Excellent Work!

### ISSUE THREAD

**Issue by Nevaeh7** [RogerQi/AlignDiff#1]
When the code will be released? Thanks!

**Comment by RogerQi** [comment]
Thanks for your interest! I am eyeing within next month or so. I have another deadline at Sep 15 and will work on code release after this date.

**Comment by Nevaeh7** [comment]
> Thanks for your interest! I am eyeing within next month or so. I have another deadline at Sep 15 and will work on code release after this date.
Hello! Could you please open source the code recently? Thank you very much!

**Comment by RogerQi** [comment]
This PR has been merged. Sorry for the delay.

I am closing the issue for now. Feel free to open new issues if you have any questions.
